import React from 'react';
import styles from './MainLayout.module.css';
import Head from 'next/head';
import { Navbar } from '../Navbar';

export const MainLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>HomePage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={`${styles.main} ${styles.className}`}>
        {children}
      </main>
    </div>
  );
};
